//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lightoxs
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileID { get; set; }
        public int FolderID { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public string Path { get; set; }
        public int TypeFile { get; set; }
        public string CSS { get; set; }
        public string Description { get; set; }
    
        public virtual Folder Folder { get; set; }
    }
}
