//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lightoxs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaTag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetaTag()
        {
            this.Pages_Meta_NTP = new HashSet<Pages_Meta_NTP>();
        }
    
        public int MetaID { get; set; }
        public string MetaTag1 { get; set; }
        public string MetaName { get; set; }
        public Nullable<int> MaxLength { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pages_Meta_NTP> Pages_Meta_NTP { get; set; }
    }
}
