//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lightoxs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NhoTimEntities : DbContext
    {
        public NhoTimEntities()
            : base("name=NhoTimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<CategoryNTP> CategoryNTPs { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Emp_Dep> Emp_Dep { get; set; }
        public virtual DbSet<Employee_Group> Employee_Group { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<MetaTag> MetaTags { get; set; }
        public virtual DbSet<Pages_Meta_NTP> Pages_Meta_NTP { get; set; }
        public virtual DbSet<PagesNTP> PagesNTPs { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<PostCatNTP> PostCatNTPs { get; set; }
        public virtual DbSet<PostPinNTP> PostPinNTPs { get; set; }
        public virtual DbSet<PostsNTP> PostsNTPs { get; set; }
        public virtual DbSet<ProductsNTP> ProductsNTPs { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<SubCategoryNTP> SubCategoryNTPs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TagsNTP> TagsNTPs { get; set; }
    }
}
