//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lightoxs
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagesNTP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PagesNTP()
        {
            this.Pages_Meta_NTP = new HashSet<Pages_Meta_NTP>();
            this.PagesNTP1 = new HashSet<PagesNTP>();
        }
    
        public int PageID { get; set; }
        public string PageName { get; set; }
        public string PageTitle { get; set; }
        public Nullable<int> FolderID { get; set; }
        public Nullable<int> PageChild { get; set; }
    
        public virtual Folder Folder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pages_Meta_NTP> Pages_Meta_NTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagesNTP> PagesNTP1 { get; set; }
        public virtual PagesNTP PagesNTP2 { get; set; }
    }
}
