//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lightoxs
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostsNTP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostsNTP()
        {
            this.TagsNTPs = new HashSet<TagsNTP>();
        }
    
        public int PostID { get; set; }
        public int FolderID { get; set; }
        public int EmpID { get; set; }
        public int CatID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string LinkFB { get; set; }
        public int Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Folder Folder { get; set; }
        public virtual PostCatNTP PostCatNTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagsNTP> TagsNTPs { get; set; }
    }
}
