//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lightoxs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsNTP
    {
        public int ProductID { get; set; }
        public int SubID { get; set; }
        public int BrandID { get; set; }
        public int EmpID { get; set; }
        public int FolderID { get; set; }
        public string Name { get; set; }
        public string SEO { get; set; }
        public string LinkFB { get; set; }
        public string ShortContent { get; set; }
        public string Content { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual SubCategoryNTP SubCategoryNTP { get; set; }
    }
}
